import { Inter } from "next/font/google";
import "./globals.css";
import '../../public/template/css/bootstrap.min.css';
import '../../public/template/css/starter-template.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <script src="/template/js/jquery.min.js"></script>
        <script src="/template/js/bootstrap.bundle.min.js"></script>
      </body>
    </html>
  );
}
